//CPP (Implementation) of "_3.pas"
#include "_3.h"
void DASDASDSDADADASDASDAS (  ) {
void DSADASDADASDASDASDSAD (  ) {
void DASDASDSDADADASDASDASDADASDASDSADA (  ) {
void DSADASDADASDASDASDSADASDASDASDASDDAS (  ) {
void DASDASDSDADADASDASDASHFGHFG (  ) {
void DSADASDADASDASDASDSADKJLLJKLJ (  ) {
void DASDASDSDADADASDASDASDADASDASDSADAASD (  ) {
void DSADASDADASDASDASDSADASDASDASDASDDASASDASD (  ) {
#define A 321
static G F = 412 ;
 } 
 } 
 } 
 } 
 } 
 } 
 } 
 } 

