PP=fpc
BASEARGS= -Fu. -Fu./../Build/SrcUnits/Includes -Fu./../Build/SrcUnits/Inet -Fu./../Build/SrcUnits/Inet/sys -Fu./../Build/SrcUnits -Fu./../Build/SrcUnits/Others -Fi./../Build/SrcUnits/Includes -Sm
RENDERARGS= -Fu./../Build/SrcUnits/DirectX -Fu./../Build/SrcUnits/OpenGL 
OUTPUTUNIXORWIN= -FU./../Build/CompiledUnits/i386-other -FE.
OPT= -gl

default:
	$(PP) $(BASEARGS) $(RENDERARGS) $(OUTPUTUNIXORWIN) $(OPT) Example6/Ex6
	$(PP) $(BASEARGS) $(RENDERARGS) $(OUTPUTUNIXORWIN) $(OPT) Example5/Ex5_4
	$(PP) $(BASEARGS) $(RENDERARGS) $(OUTPUTUNIXORWIN) $(OPT) Example5/Ex5_2
	$(PP) $(BASEARGS) $(RENDERARGS) $(OUTPUTUNIXORWIN) $(OPT) Example5/Ex5
	$(PP) $(BASEARGS) $(RENDERARGS) $(OUTPUTUNIXORWIN) $(OPT) Example4/Ex4_3
	$(PP) $(BASEARGS) $(RENDERARGS) $(OUTPUTUNIXORWIN) $(OPT) Example4/Ex4_2
	$(PP) $(BASEARGS) $(RENDERARGS) $(OUTPUTUNIXORWIN) $(OPT) Example4/Ex4_1
	$(PP) $(BASEARGS) $(RENDERARGS) $(OUTPUTUNIXORWIN) $(OPT) Example3/Ex3
	$(PP) $(BASEARGS) $(RENDERARGS) $(OUTPUTUNIXORWIN) $(OPT) Example2/Ex2
	$(PP) $(BASEARGS) $(RENDERARGS) $(OUTPUTUNIXORWIN) $(OPT) Example1/Ex1
